PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ff: <http://www.semanticweb.org/ontologies/2023/1/fathers_father#>
INSERT DATA
{
    ff:Jacob a ff:Male.
    ff:Isaac a ff:Male;
        ff:father_of ff:Jacob.
}